---
- name: Install unattended-upgrades (Debian/Ubuntu)
  package:
    name: unattended-upgrades
    state: present
  when: 
    - ansible_os_family == "Debian"
    - hardening_enable_auto_updates | bool

- name: Enable automatic updates (Debian/Ubuntu)
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
  when: 
    - ansible_os_family == "Debian"
    - hardening_enable_auto_updates | bool

- name: Install dnf-automatic (RedHat)
  package:
    name: dnf-automatic
    state: present
  when: 
    - ansible_os_family == "RedHat"
    - hardening_enable_auto_updates | bool

- name: Enable and start dnf-automatic timer
  systemd:
    name: dnf-automatic.timer
    enabled: yes
    state: started
  when: 
    - ansible_os_family == "RedHat"
    - hardening_enable_auto_updates | bool