---
- name: Ensuer GRUB is installed
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX=""'
    create: yes
  when: hardening_grub_manage | bool

- name: Add kernel parameters to GRUB
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="(.*)"'
    line: 'GRUB_CMDLINE_LINUX="\1 {{ item }}"'
    backrefs: yes
  loop: "{{ hardening_grub_kernel_params }}"
  when: hardening_grub_manage | bool
  notify: Update GRUB