---
- name: Gather service facts
  service_facts:

- name: Stop and disable unnecessary services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  loop: "{{ hardening_remove_services  }}"
  when: 
    - item not in hardening_exclude_services
    - item in ansible_facts.services

- name: Remove unnecessary packages
  package:
    name: "{{ item }}"
    state: absent
  loop: "{{ hardening_remove_packages  }}"
  when:
    - item not in hardening_exclude_packages 
    - item in ansible_facts.packages